FROM node:16-slim

RUN apt-get update && apt-get install -y -q --no-install-recommends libfontconfig1

WORKDIR /usr/src/demo

RUN npm init -y
RUN npm i --save skia-canvas

ENTRYPOINT [ "node", "-e", "require('skia-canvas'); console.log('what bug?');" ]
